### PR TITLE
Readme editing

### PR DESCRIPTION
**Pull request by n-k-a**
I've just made a basic outline for the README. If anyone who focused on the junits or development of the controller/model could add in more detail, that would be good.

### CODE REVIEW

**Review by karina-talibzhanova — CHANGES_REQUESTED** [review]
Please remove the kermit dancing gif - trust me, I love it, but Cathy might not

**Comment by Dioti** [comment]
> 
> 
> Please remove the kermit dancing gif - trust me, I love it, but Cathy might not

cant believe you'd do this

**Comment by n-k-a** [comment]
> 
> 
> Please remove the kermit dancing gif - trust me, I love it, but Cathy might not

Done

**Review by karina-talibzhanova — APPROVED** [review]
Nice

**Pull request merged**
